kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: download
    image: alpine
    commands:
      - ./scripts/download
  - name: docker  
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: rancher/calico-cni
      tag: ${DRONE_TAG}
    when:
      instance:
        - drone-publish.rancher.io
      event: tag
